# Generated by Django 4.2.30 on 2026-05-07 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leaf_vibration", models.FloatField()),
                ("pollen_scent_complexity", models.IntegerField()),
                ("bioluminescence_intensity", models.FloatField()),
                ("root_signal_strength", models.FloatField()),
                ("growth_rate", models.FloatField()),
                ("ambient_temperature", models.FloatField()),
                ("soil_moisture", models.FloatField()),
                ("sunlight_exposure", models.FloatField()),
                ("symbiotic_fungus", models.IntegerField()),
                ("result", models.CharField(max_length=100)),
                ("best_model", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
